SELECT SYSDATE, CURRENT_TIMESTAMP FROM DUAL
SELECT EXTRACT(MONTH FROM PAYMENT_DATE) AS payment_month FROM PAYMENT;
SELECT EXTRACT(QUATER FROM PAYMENT_DATE) AS payment_month FROM PAYMENT;
SELECT EXTRACT(YEAR FROM PAYMENT_DATE) AS payment_month FROM PAYMENT;