CREATE TABLE PAYMENT (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    AMOUNT NUMBER(10),
    MODE_OF_PAYMENT VARCHAR(25),
    PAYMENT DATE
);

INSERT INTO PAYMENT VALUES(1, 60, 'Cash', TO_DATE('2020-09-24', 'YYYY-MM-DD'));
INSERT INTO PAYMENT VALUES(2, 25, 'Debit Card', TO_DATE('2020-09-24', 'YYYY-MM-DD'));
INSERT INTO PAYMENT VALUES(3, 60, 'Cash', TO_DATE('2020-09-24', 'YYYY-MM-DD'));
INSERT INTO PAYMENT VALUES(4, 60, 'Credit Card', TO_DATE('2020-09-24', 'YYYY-MM-DD'));

SELECT * FROM PAYMENT;

ALTER TABLE PAYMENT RENAME COLUMN PAYMENT TO PAYMENT_DATE;

SELECT MODE_OF_PAYMENT, SUM(AMOUNT) AS TOTAL FROM PAYMENT GROUP BY MODE_OF_PAYMENT ORDER BY TOTAL ASC;

SELECT MODE_OF_PAYMENT, COUNT(AMOUNT) AS TOTAL FROM PAYMENT GROUP BY MODE_OF_PAYMENT HAVING COUNT(AMOUNT) >= 2 ORDER BY TOTAL DESC


