-- Create a Student table and insert values:


CREATE TABLE DEPTCST( 
    SNO VARCHAR(2), 
    NAME VARCHAR(10), 
    STUROLL VARCHAR(10),
    SEC VARCHAR(1), 
    AGE NUMBER(3) 
)

INSERT INTO DEPTCST VALUES(01, 'SRIJA', '1' ,A, 20)
INSERT INTO DEPTCST VALUES(02, 'PRITAM', '2', A, 21)
INSERT INTO DEPTCST VALUES(03, 'ANIL', '3', B,  21)
INSERT INTO DEPTCST VALUES(04, 'RAJ', '4', B, 20)